# Generated by Django 6.0.4 on 2026-04-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rupay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
