# Generated by Django 6.0.4 on 2026-04-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rupayapp', '0002_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='operator',
        ),
        migrations.DeleteModel(
            name='Operator',
        ),
    ]
